controller_manager:
  ros__parameters:

    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - rm501_joint1
      - rm501_joint2
      - rm501_joint3
      - rm501_joint4
      - rm501_joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      rm501_joint1: { trajectory: 0.2, goal: 0.1 }
      rm501_joint2: { trajectory: 0.2, goal: 0.1 }
      rm501_joint3: { trajectory: 0.2, goal: 0.1 }
      rm501_joint4: { trajectory: 0.2, goal: 0.1 }
      rm501_joint5: { trajectory: 0.2, goal: 0.1 }


forward_velocity_controller:
  ros__parameters:
    joints:
      - rm501_joint1
      - rm501_joint2
      - rm501_joint3
      - rm501_joint4
      - rm501_joint5
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - rm501_joint1
      - rm501_joint2
      - rm501_joint3
      - rm501_joint4
      - rm501_joint5




